### PR TITLE
Fix broken API docs link and tidy up a little Python doc logic

### PR DESCRIPTION
**Pull request by iosonofabio**
This PR aims at closing igraph/python-igraph#573 and igraph/python-igraph#575 in the immediate future. A separate PR to actually fix the broken link in the `python-igraph` repo will follow (tomorrow or so). That PR will NOT require immediate further intervention on this repo.

This PR also tidies up the Python docs a little. From version 0.10 onwards the Python docs are built by a single call to Sphinx, therefore it makes more sense to stop separating between API and "tutorials". That transition, which was performed a few months back via sphinx extensions, is consistent with moving towards readthedocs.org or similar hosting platform. Here, we store the python docs for versions 0.10 and later in `/python/versions/XXX`, with the APIs in `/python/versions/XXX/api`. In connection to that, there is now only one single postprocessing script that handles all python docs. While not pretty, that script is alright given current time constraints.

I have not pushed the `docs` folder itself to avoid visual cluttering, but @ntamas if you prefer I can definitely add the generated docs to this PR and merge. Otherwise, if you prefer, you can generate the docs yourself, push them to this PR, and merge.

### CODE REVIEW

**Comment by iosonofabio** [comment]
Okay, ready for review @ntamas - sorry for the wait. `make devserver` runs here, all C, R, python docs are built for all versions (old and new), the resulting files are processed by Jekyll and the webserver runs and serves the correct links as far as I could find.

**Review by ntamas — APPROVED** [review]

**Comment by ntamas** [comment]
@iosonofabio Thanks, I'm regenerating the docs on my end and it seems good now. One thing that I want to do before publishing the new version is to go through all the links on the homepage with a tool like [linkchecker](https://linkchecker.github.io/linkchecker/man/linkchecker.html) to make sure that there are no broken links anywhere. I'm setting up the infrastructure for that now; preliminary results indicate only minor errors like this that I haven't followed up yet:

```

URL        `genindex.html'
Name       `Index'
Parent URL http://localhost:4000/python/tutorial/latest/, line 234, col 8
Real URL   http://localhost:4000/python/tutorial/latest/genindex.html
Check time 3.111 seconds
Size       306B
Result     Error: 404 Not Found

URL        `py-modindex.html'
Name       `Module Index'
Parent URL http://localhost:4000/python/tutorial/latest/, line 235, col 8
Real URL   http://localhost:4000/python/tutorial/latest/py-modindex.html
Check time 3.631 seconds
Size       309B
Result     Error: 404 Not Found
```

This is only for`latest`, not for any of the concrete versions, so it's probably only a redirection issue. Anyhow, I'll take care of this.

**Comment by ntamas** [comment]
All looks fine. Apparently, `py-modindex.html` and `genindex.html` are supposed to be generated by Sphinx for API documentation, but we use PyDoctor instead and we simply hide these two links from the HTML using CSS.

**Comment by ntamas** [comment]
@iosonofabio I see that you removed `python/index.html` from the docs and essentially replaced it with `python/versions/latest/index.html`. I am going to add a redirect from the old URL because it might be the case that lots of people have this in their bookmarks, plus there are internal links within the homepage that point to this URL.

**Comment by iosonofabio** [comment]
Please do. I tried but couldn't manage to do it... Symlinking an existing folder does a different thing 😋

**Pull request merged**
