### PR TITLE
Added workshop webpage.

### PR DESCRIPTION
**Pull request by vtraag**
This is the draft for the webpage for the workshop we're organising. All the essential information is there, but I'm not sure how to best include this in the system. Perhaps it could be better located elsewhere? I'm also not sure how this can best be turned into some link, such as https://igraph.org/workshop.html.

### CODE REVIEW

**Comment by ntamas** [comment]
Before proceeding further: have you considered simply creating a completely separate site that we could host at, say, `https://workshop.igraph.org`, using a standalone Jekyll template like [this one](https://github.com/evanwill/workshop-template)? We could then simply link to the workshop site from a news item or the menu bar, and then you are not constrained by our current site infra.

**Comment by vtraag** [comment]
Thanks! I'm happy with just using the current page. As far as I'm concerned we can simply merge and deploy and take a closer look.

**Comment by szhorvat** [comment]
Link on the last logo is broken.

**Comment by ntamas** [comment]
Fixed the broken link. At the same time I realized that you cannot link to http images from an https webpage with Firefox if the "HTTPS everywhere" option is turned on, so that's why I'm not seeing some of the logos. One more reason to host the logos locally.

**Comment by vtraag** [comment]
> Perhaps add the names of attendees (package names), not just their logos?

Sorry, just saw your comments here now. I'm fine with adding the names of the attendees as well. Let me do that here: https://github.com/igraph/igraph.org/pull/59.

**Comment by ntamas** [comment]
Done, deployed.

**Comment by szhorvat** [comment]
> > Perhaps add the names of attendees (package names), not just their logos?
> 
> Sorry, just saw your comments here now. I'm fine with adding the names of the attendees as well. Let me do that here: #59.

I'm sorry, I think you misunderstood. I meant adding the names of the packages, not just their logos. I can't tell what is what from just the logos. I didn't mean adding people's names.

**Pull request merged**
